RDMA/bng_re: Remove prefetch instruction
The prefetch instruction is meant to speed up access to memory referenced
by its address argument. In the bng_re code path, it has no effect,
because the pointer refers to a function that is executed immediately
afterward.

The issue was identified due to the following kbuild compilation error:

  drivers/infiniband/hw/bng_re/bng_fw.c: In function 'bng_re_creq_irq':
    drivers/infiniband/hw/bng_re/bng_fw.c:278:9: error: implicit
    declaration of function 'prefetch' [-Wimplicit-function-declaration]
      278 |     prefetch(bng_re_get_qe(hwq, sw_cons, NULL));
          |     ^~~~~~~~

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202511260607.Kuxn4NnN-lkp@intel.com/
Fixes: 4f830cd8d7fe ("RDMA/bng_re: Add infrastructure for enabling Firmware channel")
Signed-off-by: Leon Romanovsky <leonro@nvidia.com>